#!/usr/perl5/bin/perl
#
# Control script for Per-Export NFS Latency Graphite Metrics
# <benr@joyent.com> 8/15/11


@SCRIPTS = ('read','write');

foreach $i (@SCRIPTS) {
        if (my $WORKER = fork()) {
                print("Forking of PID $WORKER for $i I/O\n");                   
                exec("./nfsv3-latency.d/nfsv3-${i}-latency.d | ./nfsv3-latency.d/graphite-nfsv3-assist.pl ${i}");
        }
}
